### PR TITLE
support base heading

### PR DESCRIPTION
**Pull request by dgeibi**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
sorry for the late reply! I didn't forget about this, thanks so much, I'll review and try to merge ASAP!

**Comment by dgeibi** [comment]
＠jonschlinkert Have you reviewed?

**Comment by jonschlinkert** [comment]
published and git tagged as 2.0. thanks again!

and sorry for the delay, I had an unusually busy week!

**Comment by dgeibi** [comment]
Thank you!

**Pull request merged**
